# Generated by Django 3.2.4 on 2021-07-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RenameField(
            model_name='productreviews',
            old_name='creator',
            new_name='user',
        ),
    ]
